### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by tytower** [pizzasgood/retrovol#13]
```
/tmp/runinterminal-19155: line 3: 19160 Floating point exception"/usr/local/bin/retrovol"
Script completed hit RETURN to close window.
```
I get this error when running the retrovol
Can you tell me what this might be thanks?

**Comment by pizzasgood** [comment]
That sounds like it's dividing by zero somewhere, probably due to having dimensions set in your config file that don't make physical sense.  I've just combed through the code and fixed what I *think* are the only two locations where this could be happening.  If v0.14.3 doesn't solve the problem, post the contents of your `~/.retrovolrc` file so I can take a look.

**Comment by tytower** [comment]
# Config file for retrovol
# This file should reside in the user's home directory and be named .retrovolrc


# Which soundcard to use
card=hw:0

# Set this to 0-2 to define a linear, logarithmic, or exponential volume scale, respectively
#scaling=0
scaling=2

# Set this to 1 to make the volume automatically mute when set to 0%, or 0 to keep it unmuted at 0%
#auto_mute=1
auto_mute=1

# Set this to 1 to make the sliders vertical, or 0 for horizontal (only applies to the main window)
#vertical=0
vertical=1

# Window position
#window_x=-1
window_x=954
#window_y=-1
window_y=448

# Window dimensions
#window_width=270
window_width=742
#window_height=256
window_height=632

# Slider dimensions
#slider_width=102
slider_width=20
#slider_height=20
slider_height=102
#slider_margin=2
slider_margin=1
#seg_thickness=2
seg_thickness=0
#seg_spacing=1
seg_spacing=0

# Slider colorscheme
#background_color=#000000
#border_color=#000000
#unlit_color=#993300
#lit_color=#FFCC00

# Enable the tray_icon
enable_tray_icon=1

# Enable the tray_menu
enable_tray_menu=1

# Background color of tray_icon (default is default GTK background color).  Note:  the commandline -bg option overrides this
#tray_icon_background_color=#CCCCCC
tray_icon_background_color=#CCCCCC

# Set this to 1 to make the slider on the tray_icon vertical, or 0 for horizontal
#tray_slider_vertical=1

# Tray slider dimensions
#tray_slider_width=20
#tray_slider_height=102
#tray_slider_offset=-1

# Which slider to link with the tray_icon, identified by numid
#tray_control=37
tray_control=1



# The numids of the sliders to display, in order.  It is okay to have comments
# after the numbers as long as the numbers are the first non-whitespace
# characters.  To get a list of the slider numids, run this command:
#    amixer controls
# NOTE:  This section must go at the end of the file!

#EXAMPLE:

#sliders:
#	37	#Master Playback Volume
#	15	#Front Playback Volume
#	3	#Surround Playback Volume

sliders:
card=hw:0
card=hw:0

**Comment by pizzasgood** [comment]
Hmm.  Are you certain you were actually testing with version 0.14.3?  Because I just tested your config file on my end, and it fails the way you describe with 0.14.2 but works with 0.14.3.  You can run `retrovol --version` to check which version you're using.

Anyway, the specific issue with the configuration is that you have `seg_thickness=0` but segments need to be at least one pixel thick.  Starting with 0.14.3 that setting is floored at 1 internally to prevent crashes, and with 0.14.4 the config gui will now also respect this limit.

**Comment by tytower** [comment]
Yeh I'll work on that thanks 
```
root# retrovol --version
retrovol 0.14.2
root# 
```
Now

```
root# retrovol --version
retrovol 0.14.4
root#
```
